// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBArECbb2HDoHwHdxyaijNLHYVvFK_OS5k',
    appId: '1:701099159601:web:df14fad0b79586f7e06510',
    messagingSenderId: '701099159601',
    projectId: 'applicationsuivi',
    authDomain: 'applicationsuivi.firebaseapp.com',
    storageBucket: 'applicationsuivi.appspot.com',
    measurementId: 'G-4BE6LRVQP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbBoQ1SkJaiKQ2Yv5Eu1siV5-o7aU4ltw',
    appId: '1:701099159601:android:fe0a87ac9fd2231ae06510',
    messagingSenderId: '701099159601',
    projectId: 'applicationsuivi',
    storageBucket: 'applicationsuivi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPgvktC3gcHjHm5akkW75ul9VmOcZuMiE',
    appId: '1:701099159601:ios:5b5a912da6881549e06510',
    messagingSenderId: '701099159601',
    projectId: 'applicationsuivi',
    storageBucket: 'applicationsuivi.appspot.com',
    iosBundleId: 'com.example.applicationsuivis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPgvktC3gcHjHm5akkW75ul9VmOcZuMiE',
    appId: '1:701099159601:ios:5b5a912da6881549e06510',
    messagingSenderId: '701099159601',
    projectId: 'applicationsuivi',
    storageBucket: 'applicationsuivi.appspot.com',
    iosBundleId: 'com.example.applicationsuivis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBArECbb2HDoHwHdxyaijNLHYVvFK_OS5k',
    appId: '1:701099159601:web:90a732887de47dc8e06510',
    messagingSenderId: '701099159601',
    projectId: 'applicationsuivi',
    authDomain: 'applicationsuivi.firebaseapp.com',
    storageBucket: 'applicationsuivi.appspot.com',
    measurementId: 'G-7Y3XGH33VL',
  );
}
